name: Notify

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:    

jobs:
  notify_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: prs_need_review
        with:
          query: |
            query needreview($owner:String!,$repo:String!) {
              pullRequests(state:OPEN, -label:"free", review:required, last: 100) {
                totalCount
              }    
            }
          variables: |   
            owner: dm-vdo
            name: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'needed reviews: ${{steps.prs_need_review.outputs.data}}'"    
