name: Notify

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:    

jobs:
  notify_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Get PRs Needing Review
        uses: octokit/graphql-action@v2.x
        id: prs_need_review
        with:
          query: |
            query needreview($queryString:String!) {
              search(type: ISSUE, query: $queryString, last: 100) {
                issueCount
              }
            }
          variables: |   
            queryString: "repo:\"dm-vdo/vdo-devel\", state:open, is:pr, -label:\"free\", review:required,"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: print output
        run: "echo 'Number of PRs requiring review in vdo-devel : ${{ steps.prs_need_review.outputs.data }}'"
          
#      - name: Send notification to Slack
#        uses: slackapi/slack-github-action@v1.24.0
#        id: slack
#        with:
#          # This data can be any valid JSON from a previous step in the GitHub Action
#          payload: |
#            {
#              "PR_MSG": "Number of PRs requiring review in vdo-devel : ${{ steps.prs_need_review.outputs.data.search.issueCount }}",
#              "PR_LINK": "https://github.com/dm-vdo/vdo-devel/pulls?q=is%3Apr+is%3Aopen+-label%3A%22free%22+review%3Arequired"
#            }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACKMSG }}
