name: Notify

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:    

jobs:
  notify_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: prs_need_review
        with:
          query: |
            query needreview($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                pullRequests(last:10, state:OPEN, review:required) {
                  totalCount
                }
              }    
            }
          variables: |   
            owner: dm-vdo
            repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'needed reviews: ${{steps.prs_need_review.outputs.data}}'"    
