name: Notify

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:    

jobs:
  notify_schedule:
    runs-on: ubuntu-latest
    steps:   
      - name: Notify Review Needed
        env:
          OWNER: dm-vdo
          REPO: vdo-devel
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          openPRs="$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query { 
              search(
                type: ISSUE, 
                query: """repo:"dm-vdo/vdo-devel", state:open, is:pr, -label:"free", review:required,""",
                last: 100,    
              ) {
                issueCount
              }
            }
          ')"
