name: Notify

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:    

jobs:
  notify_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Get All PRs
        env:
          OWNER: dm-vdo
          REPO: vdo-devel
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          openPRs="$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query { 
              search(
                type: ISSUE, 
                query: """repo:"dm-vdo/vdo-devel", state:open, is:pr, -label:"free",""",
                last: 100,    
              ) {
                pullRequests: edges {
                  pullRequest: node {
                    ... on PullRequest {
                      assignees {
                        edges {
                          assignee: node {
                            name
                          }
                        }
                      }
                      reviewDecision
                      reviewRequests {
                        edges {
                          reviewRequest: node {
                            requestedReviewer {
                              ... on User {
                                name
                              }
                            }
                          }
                        }
                      }
                      reviews {
                        edges {
                          review: node {
                            author {
                              name
                            }
                            state
                          }
                        }
                      }
                      title                                      
                    }
                  }
                }
              }
            }
          ')"                 
