name: Notify

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:    

jobs:
  notify_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Get All PRs
        env:
          OWNER: bjohnsto
          REPO: vdo-devel
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          numOpenPRs="$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            search(
              type: ISSUE, 
              query: """repo:"dm-vdo/vdo-devel", state:open, is:pr, -label:"free",""",
              last: 100,    
            ) {
              pullRequests: edges {
                totalCount
                pullRequest: node {
                  id
                  url
                  title
                }
              }
            }
          ' --jq '.data.pullRequests.totalCount')"
                 
